language: python
python:
- '3.6'
services:
  - postgresql
before_script:
  - psql -c 'create database course_test_db;' -U postgres
install:
- pip install -r requirements/staging.txt
script:
- coverage run manage.py test && flake8
after_success:
- codecov