# Generated by Django 2.2.6 on 2019-11-09 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191103_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e90a6528-9498-4191-b30b-f3cd4193b3f8'), editable=False),
        ),
    ]
