# Generated by Django 2.2.6 on 2019-11-14 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191113_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('ab895ea7-57fd-4f88-b54a-773529ad8512'), editable=False),
        ),
    ]
